export const EXPENSE_BUCKET_ALIASES: Array<[string, string]> = [
  ["food & drink", "Food & Drink"],
  ["makan", "Food & Drink"],
  ["food", "Food & Drink"],
  ["minum", "Food & Drink"],
  ["kopi", "Food & Drink"],
  ["ngopi", "Food & Drink"],
  ["restoran", "Food & Drink"],
  ["resto", "Food & Drink"],
  ["groceries", "Food & Drink"],
  ["grocery", "Food & Drink"],
  ["sembako", "Food & Drink"],
  ["dapur", "Food & Drink"],
  ["belanja dapur", "Food & Drink"],
  ["sayur", "Food & Drink"],
  ["buah", "Food & Drink"],
  ["beras", "Food & Drink"],
  ["lauk", "Food & Drink"],
  ["snack", "Food & Drink"],
  ["transport", "Transport"],
  ["transportation", "Transport"],
  ["transportasi", "Transport"],
  ["bensin", "Transport"],
  ["bbm", "Transport"],
  ["parkir", "Transport"],
  ["tol", "Transport"],
  ["ojek", "Transport"],
  ["ojol", "Transport"],
  ["gojek", "Transport"],
  ["grab", "Transport"],
  ["taxi", "Transport"],
  ["taksi", "Transport"],
  ["kereta", "Transport"],
  ["krl", "Transport"],
  ["mrt", "Transport"],
  ["lrt", "Transport"],
  ["bus", "Transport"],
  ["transjakarta", "Transport"],
  ["bills", "Bills"],
  ["tagihan", "Bills"],
  ["listrik", "Bills"],
  ["air", "Bills"],
  ["internet", "Bills"],
  ["bpjs", "Bills"],
  ["wifi", "Bills"],
  ["pulsa", "Bills"],
  ["token", "Bills"],
  ["cicilan", "Bills"],
  ["kredit", "Bills"],
  ["sewa", "Bills"],
  ["asuransi", "Bills"],
  ["pajak", "Bills"],
  ["tax", "Bills"],
  ["kesehatan", "Bills"],
  ["health", "Bills"],
  ["medical", "Bills"],
  ["dokter", "Bills"],
  ["klinik", "Bills"],
  ["rumah sakit", "Bills"],
  ["apotek", "Bills"],
  ["obat", "Bills"],
  ["pendidikan", "Bills"],
  ["education", "Bills"],
  ["sekolah", "Bills"],
  ["kuliah", "Bills"],
  ["kampus", "Bills"],
  ["spp", "Bills"],
  ["les", "Bills"],
  ["kursus", "Bills"],
  ["tuition", "Bills"],
  ["entertainment", "Entertainment"],
  ["hiburan", "Entertainment"],
  ["nongkrong", "Entertainment"],
  ["game", "Entertainment"],
  ["gaming", "Entertainment"],
  ["netflix", "Entertainment"],
  ["spotify premium", "Entertainment"],
  ["spotify", "Entertainment"],
  ["youtube premium", "Entertainment"],
  ["steam", "Entertainment"],
  ["bioskop", "Entertainment"],
  ["konser", "Entertainment"],
  ["hobi", "Entertainment"],
  ["liburan", "Entertainment"],
  ["travel", "Entertainment"],
  ["traveling", "Entertainment"],
  ["hotel", "Entertainment"],
  ["tiket", "Entertainment"],
  ["pesawat", "Entertainment"],
  ["staycation", "Entertainment"],
  ["others", "Others"],
  ["other", "Others"],
  ["belanja", "Others"],
  ["shopping", "Others"],
  ["fashion", "Others"],
  ["pakaian", "Others"],
  ["baju", "Others"],
  ["skincare", "Others"],
  ["kosmetik", "Others"],
  ["elektronik", "Others"],
  ["gadget", "Others"],
  ["kebutuhan rumah", "Others"],
  ["keluarga", "Others"],
  ["istri", "Others"],
  ["suami", "Others"],
  ["anak", "Others"],
  ["ortu", "Others"],
  ["orang tua", "Others"],
  ["rumah tangga", "Others"],
  ["kebersihan", "Others"],
  ["perabot", "Others"],
  ["furnitur", "Others"],
  ["donasi", "Others"],
  ["zakat", "Others"],
  ["amal", "Others"],
  ["sedekah", "Others"],
  ["pet", "Others"],
  ["hewan", "Others"],
  ["kucing", "Others"],
  ["anjing", "Others"],
  ["hadiah", "Others"],
  ["gift", "Others"]
];

export const INCOME_CATEGORY_ALIASES: Record<string, string> = {
  gaji: "Salary",
  salary: "Salary",
  payroll: "Salary",
  bonus: "Bonus",
  thr: "Bonus",
  insentif: "Bonus",
  komisi: "Bonus",
  freelance: "Freelance",
  freelancer: "Freelance",
  project: "Freelance",
  proyek: "Freelance",
  client: "Freelance",
  nabung: "Savings",
  tabungan: "Savings",
  saving: "Savings",
  pemasukan: "Other Income",
  pendapatan: "Other Income",
  income: "Other Income",
  "transfer masuk": "Other Income"
};
