export const HELP_TEXT = [
  "💼 Finance AI bisa Boss pakai lewat chat biasa:",
  "",
  "📝 Catat transaksi",
  "- Contoh: `makan siang 45rb`, `gaji 9,2jt`, atau `beli bensin 100rb`.",
  "- Setelah itu Boss bisa balas `simpan`, `edit 50rb`, atau `buang`.",
  "",
  "📊 Laporan",
  "- Harian: `laporan hari ini` atau `/daily report`.",
  "- Mingguan: `laporan minggu ini` atau `/weekly report`.",
  "- Bulanan: `/monthly report`, `/calendar report`, atau `/cashflow report`.",
  "- Menu report: `/report`.",
  "",
  "📌 Kategori pengeluaran",
  "- Atur kategori dan limit bulanan: `/budget set`.",
  "- Lihat kategori tersimpan: `lihat list kategori budget` atau `/budget list`.",
  "",
  "🎯 Target keuangan",
  "- Buat target: `/set goal`.",
  "- Tambah setoran target: `/goal add` atau `nabung 500rb`.",
  "- Cek progress: `/goal status`, `progress goal saya`, atau `lihat timeline`.",
  "",
  "⏰ Reminder",
  "- Contoh: `status reminder aku`, `matikan reminder budget`, atau `pause reminder 12 jam`.",
  "",
  "💼 Aset dan portfolio",
  "- Tambah aset: `/tambah aset`.",
  "- Contoh: `catat tabungan 10jt`, `catat emas`, `catat saham BBCA 2 lot harga 9000`, atau `catat properti rumah 300jt`.",
  "- Cek portfolio: `portfolio`, `aset saya berapa sekarang`, atau `komposisi aset`.",
  "",
  "📰 Market dan news",
  "- Contoh: `harga emas hari ini`, `harga BBCA hari ini`, atau `berita finance hari ini`.",
  "",
  "Ketik `/help` kapan pun untuk lihat menu ini lagi."
].join("\n");
