export const HELP_TEXT = [
  "Perintah yang tersedia:",
  "- Catat transaksi: contoh `makan siang 45000` atau `gaji 5000000`",
  "- Edit transaksi: `ubah kopi tadi jadi 20000`",
  "- Hapus transaksi: `hapus transaksi listrik` / `hapus yang barusan`",
  "- Paksa kategori bucket: `bayar spotify 50000 kategori entertainment`",
  "- Natural budget: `budget makan 2 juta/bulan`",
  "- Natural goal: `mau nabung 50 juta`",
  "- Portfolio: `Tambah saham BBCA 10 lot harga 9000`, `portfolio`",
  "- Market: `Harga BBCA hari ini`, `BTC sekarang berapa?`, `Harga emas hari ini`",
  "- News: `Berita finance hari ini`, `Ada news penting tentang aset aku gak?`",
  "- Smart allocation: `Sisa uang bulan ini sebaiknya kemana?`",
  "- Financial freedom: `Aktifkan financial freedom`, `pengeluaran aku 8 juta/bulan`, `aku mau bebas finansial 15 tahun lagi`",
  "- Wealth projection: `kalau nabung 2 juta/bulan 5 tahun jadi berapa`",
  "- `/report daily`",
  "- `/report weekly`",
  "- `/report monthly`",
  "- `/insight`",
  "- `/advice <pertanyaan>`",
  "- `/budget set <kategori> <limit>`",
  "- `/goal set <target>`",
  "- `/goal status`",
  "- `/help`"
].join("\n");
