UPDATE `User`
SET `budgetMode` = NULL
WHERE `budgetMode` = 'AUTO_FROM_TRANSACTIONS';

ALTER TABLE `User`
MODIFY `budgetMode` ENUM('MANUAL_PLAN', 'GUIDED_PLAN') NULL;

UPDATE `ExpensePlan`
SET `source` = 'MANUAL_USER_PLAN'
WHERE `source` = 'AUTO_GENERATED_LATER';

ALTER TABLE `ExpensePlan`
MODIFY `source` ENUM('MANUAL_USER_PLAN', 'GUIDED_ONBOARDING_PLAN') NOT NULL;
